#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const GAMES = [
  { id: "n-back", component: "NBack", import: "NBack" },
  { id: "stroop", component: "Stroop", import: "Stroop" },
  { id: "card-matching", component: "CardMatching", import: "CardMatching" },
  { id: "reaction-time", component: "ReactionTime", import: "ReactionTime" },
  { id: "quick-math", component: "QuickMath", import: "QuickMath" },
  { id: "simon-says", component: "SimonSays", import: "SimonSays" },
  { id: "pattern-matrix", component: "PatternMatrix", import: "PatternMatrix" },
  { id: "working-memory-grid", component: "WorkingMemoryGrid", import: "WorkingMemoryGrid" },
  { id: "schulte-table", component: "SchulteTable", import: "SchulteTable" },
  { id: "tower-of-hanoi", component: "TowerOfHanoi", import: "TowerOfHanoi" },
  { id: "ball-sort", component: "BallSort", import: "BallSort" },
  { id: "water-jugs", component: "WaterJugs", import: "WaterJugs" },
  { id: "maze", component: "Maze", import: "Maze" },
  { id: "mental-rotation", component: "MentalRotation", import: "MentalRotation" },
  { id: "number-sequence", component: "NumberSequence", import: "NumberSequence" },
  { id: "word-scramble", component: "WordScramble", import: "WordScramble" },
  { id: "dual-task", component: "DualTask", import: "DualTask" },
  { id: "visual-search", component: "VisualSearch", import: "VisualSearch" },
  { id: "anagram-solver", component: "AnagramSolver", import: "AnagramSolver" },
  { id: "trail-making", component: "TrailMaking", import: "TrailMaking" },
  { id: "delayed-recall", component: "DelayedRecall", import: "DelayedRecall" },
  { id: "logic-puzzles", component: "LogicPuzzles", import: "LogicPuzzles" },
];

const routeDir = path.join(__dirname, "../src/routes/games");

for (const game of GAMES) {
  const fileName = `${game.id}.tsx`;
  const filePath = path.join(routeDir, fileName);
  const title = game.import.replace(/([A-Z])/g, " $1").trim();

  // Use a URL-search-param approach that avoids the strict from-path typing
  // until routeTree.gen.ts is regenerated by the dev server.
  const content = `import { createFileRoute } from "@tanstack/react-router";
import { GameShell } from "@/features/games/components/GameShell";
import ${game.import} from "@/features/games/games/${game.import}";
import { GAME_MAP } from "@/features/games/data/gameRegistry";

export const Route = createFileRoute("/games/${game.id}")({
  validateSearch: (search: Record<string, unknown>) => ({
    level: Math.min(
      Math.max(1, parseInt(String(search["level"] ?? "1"), 10) || 1),
      10,
    ),
  }),
  head: () => ({
    meta: [
      { title: "${title} | SmritiSetu" },
      { name: "description", content: "Cognitive training game on SmritiSetu." },
    ],
  }),
  component: ${game.component}Page,
});

function ${game.component}Page() {
  const { level } = Route.useSearch();
  const game = GAME_MAP.get("${game.id}")!;
  return (
    <GameShell game={game} level={level}>
      <${game.import} level={level} />
    </GameShell>
  );
}
`;

  fs.writeFileSync(filePath, content, "utf8");
  console.log(`Updated: ${fileName}`);
}

console.log(`\nDone! Updated ${GAMES.length} game route files.`);
