/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CalmRouteImport } from './routes/calm'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicationRouteImport } from './routes/medication'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as CaregiverAddPatientRouteImport } from './routes/caregiver_.add-patient'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesAnagramSolverRouteImport } from './routes/games/anagram-solver'
import { Route as GamesBallSortRouteImport } from './routes/games/ball-sort'
import { Route as GamesCardMatchingRouteImport } from './routes/games/card-matching'
import { Route as GamesCulturalObjectRecognitionRouteImport } from './routes/games/cultural-object-recognition'
import { Route as GamesDailyRoutineRecallRouteImport } from './routes/games/daily-routine-recall'
import { Route as GamesDelayedRecallRouteImport } from './routes/games/delayed-recall'
import { Route as GamesDualTaskRouteImport } from './routes/games/dual-task'
import { Route as GamesLogicPuzzlesRouteImport } from './routes/games/logic-puzzles'
import { Route as GamesMazeRouteImport } from './routes/games/maze'
import { Route as GamesMentalRotationRouteImport } from './routes/games/mental-rotation'
import { Route as GamesNBackRouteImport } from './routes/games/n-back'
import { Route as GamesNumberSequenceRouteImport } from './routes/games/number-sequence'
import { Route as GamesPatternMatrixRouteImport } from './routes/games/pattern-matrix'
import { Route as GamesQuickMathRouteImport } from './routes/games/quick-math'
import { Route as GamesReactionTimeRouteImport } from './routes/games/reaction-time'
import { Route as GamesSchulteTableRouteImport } from './routes/games/schulte-table'
import { Route as GamesSimonSaysRouteImport } from './routes/games/simon-says'
import { Route as GamesStroopRouteImport } from './routes/games/stroop'
import { Route as GamesTowerOfHanoiRouteImport } from './routes/games/tower-of-hanoi'
import { Route as GamesTrailMakingRouteImport } from './routes/games/trail-making'
import { Route as GamesVisualSearchRouteImport } from './routes/games/visual-search'
import { Route as GamesWaterJugsRouteImport } from './routes/games/water-jugs'
import { Route as GamesWordScrambleRouteImport } from './routes/games/word-scramble'
import { Route as GamesWorkingMemoryGridRouteImport } from './routes/games/working-memory-grid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalmRoute = CalmRouteImport.update({
  id: '/calm',
  path: '/calm',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationRoute = MedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverAddPatientRoute = CaregiverAddPatientRouteImport.update({
  id: '/caregiver_/add-patient',
  path: '/caregiver/add-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesAnagramSolverRoute = GamesAnagramSolverRouteImport.update({
  id: '/anagram-solver',
  path: '/anagram-solver',
  getParentRoute: () => GamesRoute,
} as any)
const GamesBallSortRoute = GamesBallSortRouteImport.update({
  id: '/ball-sort',
  path: '/ball-sort',
  getParentRoute: () => GamesRoute,
} as any)
const GamesCardMatchingRoute = GamesCardMatchingRouteImport.update({
  id: '/card-matching',
  path: '/card-matching',
  getParentRoute: () => GamesRoute,
} as any)
const GamesCulturalObjectRecognitionRoute =
  GamesCulturalObjectRecognitionRouteImport.update({
    id: '/cultural-object-recognition',
    path: '/cultural-object-recognition',
    getParentRoute: () => GamesRoute,
  } as any)
const GamesDailyRoutineRecallRoute = GamesDailyRoutineRecallRouteImport.update({
  id: '/daily-routine-recall',
  path: '/daily-routine-recall',
  getParentRoute: () => GamesRoute,
} as any)
const GamesDelayedRecallRoute = GamesDelayedRecallRouteImport.update({
  id: '/delayed-recall',
  path: '/delayed-recall',
  getParentRoute: () => GamesRoute,
} as any)
const GamesDualTaskRoute = GamesDualTaskRouteImport.update({
  id: '/dual-task',
  path: '/dual-task',
  getParentRoute: () => GamesRoute,
} as any)
const GamesLogicPuzzlesRoute = GamesLogicPuzzlesRouteImport.update({
  id: '/logic-puzzles',
  path: '/logic-puzzles',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMazeRoute = GamesMazeRouteImport.update({
  id: '/maze',
  path: '/maze',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMentalRotationRoute = GamesMentalRotationRouteImport.update({
  id: '/mental-rotation',
  path: '/mental-rotation',
  getParentRoute: () => GamesRoute,
} as any)
const GamesNBackRoute = GamesNBackRouteImport.update({
  id: '/n-back',
  path: '/n-back',
  getParentRoute: () => GamesRoute,
} as any)
const GamesNumberSequenceRoute = GamesNumberSequenceRouteImport.update({
  id: '/number-sequence',
  path: '/number-sequence',
  getParentRoute: () => GamesRoute,
} as any)
const GamesPatternMatrixRoute = GamesPatternMatrixRouteImport.update({
  id: '/pattern-matrix',
  path: '/pattern-matrix',
  getParentRoute: () => GamesRoute,
} as any)
const GamesQuickMathRoute = GamesQuickMathRouteImport.update({
  id: '/quick-math',
  path: '/quick-math',
  getParentRoute: () => GamesRoute,
} as any)
const GamesReactionTimeRoute = GamesReactionTimeRouteImport.update({
  id: '/reaction-time',
  path: '/reaction-time',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSchulteTableRoute = GamesSchulteTableRouteImport.update({
  id: '/schulte-table',
  path: '/schulte-table',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSimonSaysRoute = GamesSimonSaysRouteImport.update({
  id: '/simon-says',
  path: '/simon-says',
  getParentRoute: () => GamesRoute,
} as any)
const GamesStroopRoute = GamesStroopRouteImport.update({
  id: '/stroop',
  path: '/stroop',
  getParentRoute: () => GamesRoute,
} as any)
const GamesTowerOfHanoiRoute = GamesTowerOfHanoiRouteImport.update({
  id: '/tower-of-hanoi',
  path: '/tower-of-hanoi',
  getParentRoute: () => GamesRoute,
} as any)
const GamesTrailMakingRoute = GamesTrailMakingRouteImport.update({
  id: '/trail-making',
  path: '/trail-making',
  getParentRoute: () => GamesRoute,
} as any)
const GamesVisualSearchRoute = GamesVisualSearchRouteImport.update({
  id: '/visual-search',
  path: '/visual-search',
  getParentRoute: () => GamesRoute,
} as any)
const GamesWaterJugsRoute = GamesWaterJugsRouteImport.update({
  id: '/water-jugs',
  path: '/water-jugs',
  getParentRoute: () => GamesRoute,
} as any)
const GamesWordScrambleRoute = GamesWordScrambleRouteImport.update({
  id: '/word-scramble',
  path: '/word-scramble',
  getParentRoute: () => GamesRoute,
} as any)
const GamesWorkingMemoryGridRoute = GamesWorkingMemoryGridRouteImport.update({
  id: '/working-memory-grid',
  path: '/working-memory-grid',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calm': typeof CalmRoute
  '/caregiver': typeof CaregiverRoute
  '/doctor': typeof DoctorRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/medication': typeof MedicationRoute
  '/memories': typeof MemoriesRoute
  '/register': typeof RegisterRoute
  '/routine': typeof RoutineRoute
  '/caregiver/add-patient': typeof CaregiverAddPatientRoute
  '/games/anagram-solver': typeof GamesAnagramSolverRoute
  '/games/ball-sort': typeof GamesBallSortRoute
  '/games/card-matching': typeof GamesCardMatchingRoute
  '/games/cultural-object-recognition': typeof GamesCulturalObjectRecognitionRoute
  '/games/daily-routine-recall': typeof GamesDailyRoutineRecallRoute
  '/games/delayed-recall': typeof GamesDelayedRecallRoute
  '/games/dual-task': typeof GamesDualTaskRoute
  '/games/logic-puzzles': typeof GamesLogicPuzzlesRoute
  '/games/maze': typeof GamesMazeRoute
  '/games/mental-rotation': typeof GamesMentalRotationRoute
  '/games/n-back': typeof GamesNBackRoute
  '/games/number-sequence': typeof GamesNumberSequenceRoute
  '/games/pattern-matrix': typeof GamesPatternMatrixRoute
  '/games/quick-math': typeof GamesQuickMathRoute
  '/games/reaction-time': typeof GamesReactionTimeRoute
  '/games/schulte-table': typeof GamesSchulteTableRoute
  '/games/simon-says': typeof GamesSimonSaysRoute
  '/games/stroop': typeof GamesStroopRoute
  '/games/tower-of-hanoi': typeof GamesTowerOfHanoiRoute
  '/games/trail-making': typeof GamesTrailMakingRoute
  '/games/visual-search': typeof GamesVisualSearchRoute
  '/games/water-jugs': typeof GamesWaterJugsRoute
  '/games/word-scramble': typeof GamesWordScrambleRoute
  '/games/working-memory-grid': typeof GamesWorkingMemoryGridRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calm': typeof CalmRoute
  '/caregiver': typeof CaregiverRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/medication': typeof MedicationRoute
  '/memories': typeof MemoriesRoute
  '/register': typeof RegisterRoute
  '/routine': typeof RoutineRoute
  '/caregiver/add-patient': typeof CaregiverAddPatientRoute
  '/games/anagram-solver': typeof GamesAnagramSolverRoute
  '/games/ball-sort': typeof GamesBallSortRoute
  '/games/card-matching': typeof GamesCardMatchingRoute
  '/games/cultural-object-recognition': typeof GamesCulturalObjectRecognitionRoute
  '/games/daily-routine-recall': typeof GamesDailyRoutineRecallRoute
  '/games/delayed-recall': typeof GamesDelayedRecallRoute
  '/games/dual-task': typeof GamesDualTaskRoute
  '/games/logic-puzzles': typeof GamesLogicPuzzlesRoute
  '/games/maze': typeof GamesMazeRoute
  '/games/mental-rotation': typeof GamesMentalRotationRoute
  '/games/n-back': typeof GamesNBackRoute
  '/games/number-sequence': typeof GamesNumberSequenceRoute
  '/games/pattern-matrix': typeof GamesPatternMatrixRoute
  '/games/quick-math': typeof GamesQuickMathRoute
  '/games/reaction-time': typeof GamesReactionTimeRoute
  '/games/schulte-table': typeof GamesSchulteTableRoute
  '/games/simon-says': typeof GamesSimonSaysRoute
  '/games/stroop': typeof GamesStroopRoute
  '/games/tower-of-hanoi': typeof GamesTowerOfHanoiRoute
  '/games/trail-making': typeof GamesTrailMakingRoute
  '/games/visual-search': typeof GamesVisualSearchRoute
  '/games/water-jugs': typeof GamesWaterJugsRoute
  '/games/word-scramble': typeof GamesWordScrambleRoute
  '/games/working-memory-grid': typeof GamesWorkingMemoryGridRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calm': typeof CalmRoute
  '/caregiver': typeof CaregiverRoute
  '/doctor': typeof DoctorRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/medication': typeof MedicationRoute
  '/memories': typeof MemoriesRoute
  '/register': typeof RegisterRoute
  '/routine': typeof RoutineRoute
  '/caregiver_/add-patient': typeof CaregiverAddPatientRoute
  '/games/anagram-solver': typeof GamesAnagramSolverRoute
  '/games/ball-sort': typeof GamesBallSortRoute
  '/games/card-matching': typeof GamesCardMatchingRoute
  '/games/cultural-object-recognition': typeof GamesCulturalObjectRecognitionRoute
  '/games/daily-routine-recall': typeof GamesDailyRoutineRecallRoute
  '/games/delayed-recall': typeof GamesDelayedRecallRoute
  '/games/dual-task': typeof GamesDualTaskRoute
  '/games/logic-puzzles': typeof GamesLogicPuzzlesRoute
  '/games/maze': typeof GamesMazeRoute
  '/games/mental-rotation': typeof GamesMentalRotationRoute
  '/games/n-back': typeof GamesNBackRoute
  '/games/number-sequence': typeof GamesNumberSequenceRoute
  '/games/pattern-matrix': typeof GamesPatternMatrixRoute
  '/games/quick-math': typeof GamesQuickMathRoute
  '/games/reaction-time': typeof GamesReactionTimeRoute
  '/games/schulte-table': typeof GamesSchulteTableRoute
  '/games/simon-says': typeof GamesSimonSaysRoute
  '/games/stroop': typeof GamesStroopRoute
  '/games/tower-of-hanoi': typeof GamesTowerOfHanoiRoute
  '/games/trail-making': typeof GamesTrailMakingRoute
  '/games/visual-search': typeof GamesVisualSearchRoute
  '/games/water-jugs': typeof GamesWaterJugsRoute
  '/games/word-scramble': typeof GamesWordScrambleRoute
  '/games/working-memory-grid': typeof GamesWorkingMemoryGridRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calm'
    | '/caregiver'
    | '/doctor'
    | '/games'
    | '/login'
    | '/medication'
    | '/memories'
    | '/register'
    | '/routine'
    | '/caregiver/add-patient'
    | '/games/anagram-solver'
    | '/games/ball-sort'
    | '/games/card-matching'
    | '/games/cultural-object-recognition'
    | '/games/daily-routine-recall'
    | '/games/delayed-recall'
    | '/games/dual-task'
    | '/games/logic-puzzles'
    | '/games/maze'
    | '/games/mental-rotation'
    | '/games/n-back'
    | '/games/number-sequence'
    | '/games/pattern-matrix'
    | '/games/quick-math'
    | '/games/reaction-time'
    | '/games/schulte-table'
    | '/games/simon-says'
    | '/games/stroop'
    | '/games/tower-of-hanoi'
    | '/games/trail-making'
    | '/games/visual-search'
    | '/games/water-jugs'
    | '/games/word-scramble'
    | '/games/working-memory-grid'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calm'
    | '/caregiver'
    | '/doctor'
    | '/login'
    | '/medication'
    | '/memories'
    | '/register'
    | '/routine'
    | '/caregiver/add-patient'
    | '/games/anagram-solver'
    | '/games/ball-sort'
    | '/games/card-matching'
    | '/games/cultural-object-recognition'
    | '/games/daily-routine-recall'
    | '/games/delayed-recall'
    | '/games/dual-task'
    | '/games/logic-puzzles'
    | '/games/maze'
    | '/games/mental-rotation'
    | '/games/n-back'
    | '/games/number-sequence'
    | '/games/pattern-matrix'
    | '/games/quick-math'
    | '/games/reaction-time'
    | '/games/schulte-table'
    | '/games/simon-says'
    | '/games/stroop'
    | '/games/tower-of-hanoi'
    | '/games/trail-making'
    | '/games/visual-search'
    | '/games/water-jugs'
    | '/games/word-scramble'
    | '/games/working-memory-grid'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calm'
    | '/caregiver'
    | '/doctor'
    | '/games'
    | '/login'
    | '/medication'
    | '/memories'
    | '/register'
    | '/routine'
    | '/caregiver_/add-patient'
    | '/games/anagram-solver'
    | '/games/ball-sort'
    | '/games/card-matching'
    | '/games/cultural-object-recognition'
    | '/games/daily-routine-recall'
    | '/games/delayed-recall'
    | '/games/dual-task'
    | '/games/logic-puzzles'
    | '/games/maze'
    | '/games/mental-rotation'
    | '/games/n-back'
    | '/games/number-sequence'
    | '/games/pattern-matrix'
    | '/games/quick-math'
    | '/games/reaction-time'
    | '/games/schulte-table'
    | '/games/simon-says'
    | '/games/stroop'
    | '/games/tower-of-hanoi'
    | '/games/trail-making'
    | '/games/visual-search'
    | '/games/water-jugs'
    | '/games/word-scramble'
    | '/games/working-memory-grid'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalmRoute: typeof CalmRoute
  CaregiverRoute: typeof CaregiverRoute
  DoctorRoute: typeof DoctorRoute
  GamesRoute: typeof GamesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MedicationRoute: typeof MedicationRoute
  MemoriesRoute: typeof MemoriesRoute
  RegisterRoute: typeof RegisterRoute
  RoutineRoute: typeof RoutineRoute
  CaregiverAddPatientRoute: typeof CaregiverAddPatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calm': {
      id: '/calm'
      path: '/calm'
      fullPath: '/calm'
      preLoaderRoute: typeof CalmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication': {
      id: '/medication'
      path: '/medication'
      fullPath: '/medication'
      preLoaderRoute: typeof MedicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver_/add-patient': {
      id: '/caregiver_/add-patient'
      path: '/caregiver/add-patient'
      fullPath: '/caregiver/add-patient'
      preLoaderRoute: typeof CaregiverAddPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/anagram-solver': {
      id: '/games/anagram-solver'
      path: '/anagram-solver'
      fullPath: '/games/anagram-solver'
      preLoaderRoute: typeof GamesAnagramSolverRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/ball-sort': {
      id: '/games/ball-sort'
      path: '/ball-sort'
      fullPath: '/games/ball-sort'
      preLoaderRoute: typeof GamesBallSortRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/card-matching': {
      id: '/games/card-matching'
      path: '/card-matching'
      fullPath: '/games/card-matching'
      preLoaderRoute: typeof GamesCardMatchingRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/cultural-object-recognition': {
      id: '/games/cultural-object-recognition'
      path: '/cultural-object-recognition'
      fullPath: '/games/cultural-object-recognition'
      preLoaderRoute: typeof GamesCulturalObjectRecognitionRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/daily-routine-recall': {
      id: '/games/daily-routine-recall'
      path: '/daily-routine-recall'
      fullPath: '/games/daily-routine-recall'
      preLoaderRoute: typeof GamesDailyRoutineRecallRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/delayed-recall': {
      id: '/games/delayed-recall'
      path: '/delayed-recall'
      fullPath: '/games/delayed-recall'
      preLoaderRoute: typeof GamesDelayedRecallRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/dual-task': {
      id: '/games/dual-task'
      path: '/dual-task'
      fullPath: '/games/dual-task'
      preLoaderRoute: typeof GamesDualTaskRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/logic-puzzles': {
      id: '/games/logic-puzzles'
      path: '/logic-puzzles'
      fullPath: '/games/logic-puzzles'
      preLoaderRoute: typeof GamesLogicPuzzlesRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/maze': {
      id: '/games/maze'
      path: '/maze'
      fullPath: '/games/maze'
      preLoaderRoute: typeof GamesMazeRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/mental-rotation': {
      id: '/games/mental-rotation'
      path: '/mental-rotation'
      fullPath: '/games/mental-rotation'
      preLoaderRoute: typeof GamesMentalRotationRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/n-back': {
      id: '/games/n-back'
      path: '/n-back'
      fullPath: '/games/n-back'
      preLoaderRoute: typeof GamesNBackRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/number-sequence': {
      id: '/games/number-sequence'
      path: '/number-sequence'
      fullPath: '/games/number-sequence'
      preLoaderRoute: typeof GamesNumberSequenceRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/pattern-matrix': {
      id: '/games/pattern-matrix'
      path: '/pattern-matrix'
      fullPath: '/games/pattern-matrix'
      preLoaderRoute: typeof GamesPatternMatrixRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/quick-math': {
      id: '/games/quick-math'
      path: '/quick-math'
      fullPath: '/games/quick-math'
      preLoaderRoute: typeof GamesQuickMathRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/reaction-time': {
      id: '/games/reaction-time'
      path: '/reaction-time'
      fullPath: '/games/reaction-time'
      preLoaderRoute: typeof GamesReactionTimeRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/schulte-table': {
      id: '/games/schulte-table'
      path: '/schulte-table'
      fullPath: '/games/schulte-table'
      preLoaderRoute: typeof GamesSchulteTableRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/simon-says': {
      id: '/games/simon-says'
      path: '/simon-says'
      fullPath: '/games/simon-says'
      preLoaderRoute: typeof GamesSimonSaysRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/stroop': {
      id: '/games/stroop'
      path: '/stroop'
      fullPath: '/games/stroop'
      preLoaderRoute: typeof GamesStroopRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/tower-of-hanoi': {
      id: '/games/tower-of-hanoi'
      path: '/tower-of-hanoi'
      fullPath: '/games/tower-of-hanoi'
      preLoaderRoute: typeof GamesTowerOfHanoiRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/trail-making': {
      id: '/games/trail-making'
      path: '/trail-making'
      fullPath: '/games/trail-making'
      preLoaderRoute: typeof GamesTrailMakingRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/visual-search': {
      id: '/games/visual-search'
      path: '/visual-search'
      fullPath: '/games/visual-search'
      preLoaderRoute: typeof GamesVisualSearchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/water-jugs': {
      id: '/games/water-jugs'
      path: '/water-jugs'
      fullPath: '/games/water-jugs'
      preLoaderRoute: typeof GamesWaterJugsRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/word-scramble': {
      id: '/games/word-scramble'
      path: '/word-scramble'
      fullPath: '/games/word-scramble'
      preLoaderRoute: typeof GamesWordScrambleRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/working-memory-grid': {
      id: '/games/working-memory-grid'
      path: '/working-memory-grid'
      fullPath: '/games/working-memory-grid'
      preLoaderRoute: typeof GamesWorkingMemoryGridRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesAnagramSolverRoute: typeof GamesAnagramSolverRoute
  GamesBallSortRoute: typeof GamesBallSortRoute
  GamesCardMatchingRoute: typeof GamesCardMatchingRoute
  GamesCulturalObjectRecognitionRoute: typeof GamesCulturalObjectRecognitionRoute
  GamesDailyRoutineRecallRoute: typeof GamesDailyRoutineRecallRoute
  GamesDelayedRecallRoute: typeof GamesDelayedRecallRoute
  GamesDualTaskRoute: typeof GamesDualTaskRoute
  GamesLogicPuzzlesRoute: typeof GamesLogicPuzzlesRoute
  GamesMazeRoute: typeof GamesMazeRoute
  GamesMentalRotationRoute: typeof GamesMentalRotationRoute
  GamesNBackRoute: typeof GamesNBackRoute
  GamesNumberSequenceRoute: typeof GamesNumberSequenceRoute
  GamesPatternMatrixRoute: typeof GamesPatternMatrixRoute
  GamesQuickMathRoute: typeof GamesQuickMathRoute
  GamesReactionTimeRoute: typeof GamesReactionTimeRoute
  GamesSchulteTableRoute: typeof GamesSchulteTableRoute
  GamesSimonSaysRoute: typeof GamesSimonSaysRoute
  GamesStroopRoute: typeof GamesStroopRoute
  GamesTowerOfHanoiRoute: typeof GamesTowerOfHanoiRoute
  GamesTrailMakingRoute: typeof GamesTrailMakingRoute
  GamesVisualSearchRoute: typeof GamesVisualSearchRoute
  GamesWaterJugsRoute: typeof GamesWaterJugsRoute
  GamesWordScrambleRoute: typeof GamesWordScrambleRoute
  GamesWorkingMemoryGridRoute: typeof GamesWorkingMemoryGridRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesAnagramSolverRoute: GamesAnagramSolverRoute,
  GamesBallSortRoute: GamesBallSortRoute,
  GamesCardMatchingRoute: GamesCardMatchingRoute,
  GamesCulturalObjectRecognitionRoute: GamesCulturalObjectRecognitionRoute,
  GamesDailyRoutineRecallRoute: GamesDailyRoutineRecallRoute,
  GamesDelayedRecallRoute: GamesDelayedRecallRoute,
  GamesDualTaskRoute: GamesDualTaskRoute,
  GamesLogicPuzzlesRoute: GamesLogicPuzzlesRoute,
  GamesMazeRoute: GamesMazeRoute,
  GamesMentalRotationRoute: GamesMentalRotationRoute,
  GamesNBackRoute: GamesNBackRoute,
  GamesNumberSequenceRoute: GamesNumberSequenceRoute,
  GamesPatternMatrixRoute: GamesPatternMatrixRoute,
  GamesQuickMathRoute: GamesQuickMathRoute,
  GamesReactionTimeRoute: GamesReactionTimeRoute,
  GamesSchulteTableRoute: GamesSchulteTableRoute,
  GamesSimonSaysRoute: GamesSimonSaysRoute,
  GamesStroopRoute: GamesStroopRoute,
  GamesTowerOfHanoiRoute: GamesTowerOfHanoiRoute,
  GamesTrailMakingRoute: GamesTrailMakingRoute,
  GamesVisualSearchRoute: GamesVisualSearchRoute,
  GamesWaterJugsRoute: GamesWaterJugsRoute,
  GamesWordScrambleRoute: GamesWordScrambleRoute,
  GamesWorkingMemoryGridRoute: GamesWorkingMemoryGridRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalmRoute: CalmRoute,
  CaregiverRoute: CaregiverRoute,
  DoctorRoute: DoctorRoute,
  GamesRoute: GamesRouteWithChildren,
  LoginRoute: LoginRoute,
  MedicationRoute: MedicationRoute,
  MemoriesRoute: MemoriesRoute,
  RegisterRoute: RegisterRoute,
  RoutineRoute: RoutineRoute,
  CaregiverAddPatientRoute: CaregiverAddPatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
