"""add medication schedules and logs

Revision ID: 261af78029f1
Revises: 7b902d0a16f9
Create Date: 2026-09-12 03:58:13.839082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261af78029f1'
down_revision: Union[str, Sequence[str], None] = '7b902d0a16f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'CUSTOM', name='medicationfrequency'), nullable=False),
    sa.Column('days_of_week', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_patient_id'), 'medication_schedules', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medication_schedules_prescription_id'), 'medication_schedules', ['prescription_id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'TAKEN', 'MISSED', 'SKIPPED', name='medicationlogstatus'), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_patient_id'), 'medication_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medication_logs_schedule_id'), 'medication_logs', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_logs_schedule_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_patient_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_medication_schedules_prescription_id'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_patient_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    # ### end Alembic commands ###
