"""add doctor and caretaker relationships

Revision ID: 28fbb7967fef
Revises: 65bd01fb1823
Create Date: 2026-09-12 02:28:40.952881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fbb7967fef'
down_revision: Union[str, Sequence[str], None] = '65bd01fb1823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caretaker_patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caretaker_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caretaker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caretaker_patients_caretaker_id'), 'caretaker_patients', ['caretaker_id'], unique=False)
    op.create_index(op.f('ix_caretaker_patients_patient_id'), 'caretaker_patients', ['patient_id'], unique=False)
    op.create_table('doctor_patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patients_doctor_id'), 'doctor_patients', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patients_patient_id'), 'doctor_patients', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_patients_patient_id'), table_name='doctor_patients')
    op.drop_index(op.f('ix_doctor_patients_doctor_id'), table_name='doctor_patients')
    op.drop_table('doctor_patients')
    op.drop_index(op.f('ix_caretaker_patients_patient_id'), table_name='caretaker_patients')
    op.drop_index(op.f('ix_caretaker_patients_caretaker_id'), table_name='caretaker_patients')
    op.drop_table('caretaker_patients')
    # ### end Alembic commands ###
