"""add notifications

Revision ID: a34ab55df34f
Revises: 261af78029f1
Create Date: 2026-09-12 04:29:26.670137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34ab55df34f'
down_revision: Union[str, Sequence[str], None] = '261af78029f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('MEDICATION', 'TASK', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'READ', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_patient_id'), 'notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_entity_id'), 'notifications', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_scheduled_for'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_patient_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
